<?php

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Plain-text defaults used to populate ACF fields on first setup.
 *
 * Markup belongs in template-parts. No value in this file contains HTML.
 */
function ghalya_default_content($screen, $language)
{
    $defaults = array(
        'en' => array(
            'home' => array(
                'hero_title' => 'Turn your passion for content into meaningful partnerships with',
                'hero_accent' => 'Ghalya.',
                'hero_intro' => 'Connect with premium brands, inspire your community through authentic experiences, and',
                'hero_intro_emphasis' => 'unlock rewards that grow with your impact.',
                'hero_eyebrow' => 'Ghalya creator program',
                'creators_alt' => 'Three Ghalya content creators',
                'earn_note' => 'Earn up to 10,000 SAR in points across 5+ brands',
                'reward_title' => 'What you’ll earn',
                'reward_amount' => '2,000 SAR',
                'reward_suffix' => 'in points',
                'reward_desktop_suffix' => 'in Ghalya loyalty points',
                'reward_detail' => 'Per campaign: 1 store visit · 2 Reels · 2 Story sets',
                'join_button' => 'Join the community',
                'explore_button' => 'Explore the program',
                'tiers_label' => 'Creator tiers',
                'tiers' => array(
                    array('label' => 'Nano', 'active' => 0),
                    array('label' => 'Micro', 'active' => 1),
                    array('label' => 'Mid', 'active' => 0),
                    array('label' => 'Macro', 'active' => 0),
                ),
                'partners_eyebrow' => 'The universe',
                'partners_title' => 'Earn and spend with our partners',
                'partners_mobile_prefix' => 'The',
                'partners_mobile_suffix' => 'Universe',
                'partners_mobile_copy' => 'Earn & spend points with our partners',
                'partners_label' => 'Ghalya partner brands',
                'benefits_eyebrow' => 'Made for creators',
                'benefits_title' => 'What’s in it for you?',
                'benefits_intro' => 'A creator partnership built around authentic stories, better reach, and rewards you can actually use.',
                'benefits' => array(
                    array('title' => 'Earn Flexible Rewards', 'description' => 'Create content about Ghalya and earn points to spend freely across partner brands.'),
                    array('title' => 'Grow Your Audience', 'description' => 'Elevate your presence and reach authentic regional followers.'),
                    array('title' => 'Unlock Premium Brand Partnerships', 'description' => 'Access paid and gift-supported collaborations with leading brands.'),
                    array('title' => 'Exclusive Product Perks', 'description' => 'Be first in line for free gifts, new product drops, and VIP invitations.'),
                ),
                'deliver_eyebrow' => 'Simple deliverables',
                'deliver_title' => 'What you’ll deliver per campaign',
                'deliverables' => array(
                    array('title' => '1 Store visit', 'description' => 'Experience the brand in person.'),
                    array('title' => '2 Reels / TikToks', 'description' => 'Post engaging short-form video content.'),
                    array('title' => '2 Story Sets', 'description' => 'Share real-time coverage and direct link tags.'),
                    array('title' => 'Fast Payout', 'description' => 'Points credited straight to your Ghalya wallet upon approval.'),
                ),
                'looking_eyebrow' => 'Ready to create?',
                'looking_title' => 'Who we’re looking for',
                'requirements' => array(
                    array('text' => 'Based in Saudi Arabia'),
                    array('text' => '1,000+ followers on social media'),
                    array('text' => 'Active creator on Instagram or TikTok'),
                ),
                'categories_title' => 'Creator categories',
                'categories' => array(
                    array('text' => 'Food'), array('text' => 'Travel'), array('text' => 'Chefs'),
                    array('text' => 'Offers & Deals'), array('text' => 'Beauty'), array('text' => 'Fitness'),
                    array('text' => 'Lifestyle'),
                ),
                'start_button' => 'Start your application',
                'faq_eyebrow' => 'FAQs',
                'faq_title' => 'Good to know',
                'faq_intro' => 'Everything you need before applying to the Ghalya Creator Program.',
                'faqs' => array(
                    array('question' => 'Is there any cost to join the Ghalya Creator Program?', 'answer' => 'No. Joining Ghalya as a creator partner is 100% free, with no registration fees, platform charges, or hidden costs.'),
                    array('question' => 'How do I receive my earnings?', 'answer' => 'Approved rewards are credited as Ghalya loyalty points to your registered Ghalya wallet.'),
                    array('question' => 'Do I need a Saudi Advertising Permit (Mawthooq)?', 'answer' => 'A valid permit is required where Saudi regulations apply to sponsored or promotional content.'),
                    array('question' => 'How long does it take for my application to be reviewed?', 'answer' => 'You can expect a reply within 14 days of submitting your application.'),
                    array('question' => 'Can Ghalya points be converted to cash?', 'answer' => 'Points are not convertible to cash. They can be redeemed with participating partner brands.'),
                    array('question' => 'Which brands are included in the program?', 'answer' => 'The program includes five or more premium retail partners, with availability varying by campaign.'),
                    array('question' => 'Can I choose which stores and brands I visit?', 'answer' => 'You can indicate preferred brands and availability in your proposal.'),
                    array('question' => 'What content rights do brands get?', 'answer' => 'Creators retain ownership and grant limited campaign usage rights as described in the terms.'),
                ),
            ),
            'profile' => array(
                'aside_title' => 'Your Ghalya application',
                'aside_intro' => 'Tell us about your audience, work, and availability. It only takes a few minutes.',
                'progress_labels' => ghalya_default_progress_labels('en'),
                'top_back_label' => 'Back home',
                'step_label' => 'Step 1 of 5',
                'title' => 'Your profile',
                'intro' => 'Start with the basics so we can match you with the right campaign tier.',
                'full_name_label' => 'Full Name',
                'full_name_placeholder' => 'Firstname Lastname',
                'instagram_label' => 'Instagram Handle',
                'instagram_placeholder' => '@instagramhandle',
                'followers_label' => 'Followers',
                'followers_choices' => ghalya_default_choice_rows(array('1-10K' => '1–10K', '10K-50K' => '10K–50K', '50K-500K' => '50K–500K', '500K+' => '500K+')),
                'city_label' => 'City',
                'city_placeholder' => 'Select city',
                'city_choices' => ghalya_default_choice_rows(array('Riyadh' => 'Riyadh', 'Jeddah' => 'Jeddah', 'Dammam' => 'Dammam', 'Other' => 'Other')),
                'category_label' => 'Content category',
                'category_choices' => ghalya_default_choice_rows(array('Food' => 'Food', 'Travel' => 'Travel', 'Chefs' => 'Chefs', 'Offers and Deals' => 'Offers & Deals', 'Beauty' => 'Beauty', 'Fitness' => 'Fitness', 'Lifestyle' => 'Lifestyle')),
                'back_button' => 'Cancel',
                'next_button' => 'Next',
            ),
            'tier' => array(
                'aside_title' => 'Your Ghalya application',
                'aside_intro' => 'Your starting tier reflects the audience range and category selected in your profile.',
                'progress_labels' => ghalya_default_progress_labels('en'),
                'top_back_label' => 'Previous',
                'step_label' => 'Step 2 of 5',
                'title' => 'Your tier',
                'intro' => 'Here is your assigned campaign starter tier.',
                'tier_name' => 'Micro Creator',
                'tier_amount' => '2,000 SAR',
                'tier_suffix' => 'in Ghalya loyalty points',
                'deliverables_label' => 'Expected Deliverables',
                'deliverables' => array(array('text' => '1 store visit'), array('text' => '2 Reels / TikToks'), array('text' => '2 Story sets')),
                'note' => 'Based on your follower count and profile category, this is your assigned campaign starter tier. Ghalya loyalty points can be redeemed at 5+ partner retail outlets in Saudi Arabia.',
                'back_button' => 'Back',
                'next_button' => 'Continue',
            ),
            'work' => array(
                'aside_title' => 'Your Ghalya application',
                'aside_intro' => 'Share the channels and content that best represent your creative point of view.',
                'progress_labels' => ghalya_default_progress_labels('en'),
                'top_back_label' => 'Previous',
                'step_label' => 'Step 3 of 5',
                'title' => 'Your work',
                'intro' => 'Add your public profiles and an example of previous branded content if available.',
                'instagram_label' => 'Instagram Profile Link',
                'instagram_placeholder' => 'Paste link here',
                'tiktok_label' => 'TikTok Profile Link',
                'tiktok_placeholder' => 'Paste link here',
                'snapchat_label' => 'Snapchat Handle',
                'snapchat_placeholder' => 'Paste link here',
                'brand_content_label' => 'Previous branded content',
                'brand_content_placeholder' => 'Paste link here',
                'add_link_button' => '+ Add another link',
                'back_button' => 'Back',
                'next_button' => 'Continue',
            ),
            'proposal' => array(
                'aside_title' => 'Your Ghalya application',
                'aside_intro' => 'Choose the brands you are excited to work with and tell us when you are free.',
                'progress_labels' => ghalya_default_progress_labels('en'),
                'top_back_label' => 'Previous',
                'step_label' => 'Step 4 of 5',
                'title' => 'Your proposal',
                'intro' => 'Pick one or more partners you would like to create for.',
                'brands_label' => 'Select Brands',
                'brand_choices' => ghalya_default_choice_rows(array('Danube' => 'Danube', 'BinDawood' => 'BinDawood', 'Delsey' => 'Delsey', 'Kipling' => 'Kipling', 'Zahrat Al Rawdah' => 'Zahrat Al Rawdah')),
                'availability_label' => 'Earliest availability',
                'back_button' => 'Back',
                'next_button' => 'Continue',
            ),
            'contact' => array(
                'aside_title' => 'One final step',
                'aside_intro' => 'Add your contact details and review the program terms before submitting.',
                'progress_labels' => ghalya_default_progress_labels('en'),
                'top_back_label' => 'Previous',
                'step_label' => 'Step 5 of 5',
                'title' => 'Contact details',
                'intro' => 'Where should the Ghalya team reach you about this campaign?',
                'email_label' => 'Email Address',
                'email_placeholder' => 'email@email.com',
                'phone_label' => 'Mobile Number',
                'phone_placeholder' => '+966 0000 0000',
                'consent_before' => 'I agree to Ghalya’s',
                'consent_link' => 'terms and conditions',
                'consent_after' => 'and allow Ghalya to contact me about this campaign.',
                'back_button' => 'Back',
                'submit_button' => 'Submit application',
            ),
            'success' => array(
                'eyebrow' => 'Application complete',
                'title' => 'Application submitted!',
                'message' => 'Thank you for your interest in joining the Ghalya community. Expect a reply within 14 days.',
                'social_handle' => '@ghalyaloyalty',
                'back_button' => 'Back to Ghalya',
            ),
            'terms' => array(
                'eyebrow' => 'Ghalya Creator Program',
                'title' => 'Terms and Conditions',
                'intro' => 'These Terms and Conditions govern the participation of content creators in the Ghalya Creator Program operated by Ghalya.',
                'sections' => array(
                    array('title' => '1. Acceptance of Terms & Eligibility', 'body' => 'By submitting an application, you represent and warrant that you are at least 18 years old and reside in the Kingdom of Saudi Arabia; that all information provided, including follower counts, links, and contact details, is accurate; and that you hold a valid Saudi Advertising Permit (Mawthooq) where legally required for sponsored or promotional digital content.'),
                    array('title' => '2. Selection & Tier Assignment', 'body' => 'Submitting an application does not guarantee acceptance. Ghalya may select creators based on campaign needs, content quality, and monthly quotas. Creator tiers are calculated from follower count, engagement rates, and content category. Ghalya may adjust tier classifications or reward amounts for future campaigns.'),
                    array('title' => '3. Campaign Deliverables & Approvals', 'body' => 'On approval for a campaign, the creator agrees to complete all assigned deliverables in accordance with the supplied brief and guidelines. Content must be submitted to Ghalya for pre-approval before public posting and remain respectful, authentic, compliant with Saudi law and cultural norms, free from third-party copyright infringement, and clearly disclosed as commercial content where required.'),
                    array('title' => '4. Rewards & Payment', 'body' => 'Compensation is issued solely as Ghalya Loyalty Points and credited to the creator’s registered Ghalya digital wallet after verification and approval of deliverables. Points are non-transferable and cannot be exchanged for cash. They may be redeemed for goods, vouchers, or services at designated partner outlets, subject to partner availability and expiration policies.'),
                    array('title' => '5. Content Rights & Usage Licensing', 'body' => 'The creator retains intellectual property ownership of original content. By posting campaign content, the creator grants Ghalya and participating brand partners a non-exclusive, worldwide, royalty-free, sublicensable license to re-share, embed, and repost submitted content across official digital channels for a standard period of 90 days following campaign completion.'),
                    array('title' => '6. Data Privacy & Communication Consent', 'body' => 'By agreeing in the application form, you allow Ghalya to collect, store, and process your personal data to evaluate your application and contact you by WhatsApp, SMS, or email about active and future campaign opportunities.'),
                ),
                'start_button' => 'Start application',
                'back_button' => 'Back home',
            ),
        ),
        'ar' => array(
            'home' => array(
                'hero_title' => 'حوّل شغفك بصناعة المحتوى إلى شراكات مثمرة مع',
                'hero_accent' => 'غالية.',
                'hero_intro' => 'تواصل مع علامات تجارية رائدة، وألهم مجتمعك من خلال تجارب أصيلة،',
                'hero_intro_emphasis' => 'واكسب مكافآت تنمو مع تأثيرك.',
                'hero_eyebrow' => 'برنامج غالية لصنّاع المحتوى',
                'creators_alt' => 'ثلاثة من صنّاع محتوى غالية',
                'earn_note' => 'اكسب حتى 10,000 ريال كنقاط عبر أكثر من 5 علامات تجارية',
                'reward_title' => 'الأرباح',
                'reward_amount' => '2,000 ريال',
                'reward_suffix' => 'كنقاط',
                'reward_desktop_suffix' => 'كنقاط ولاء في غالية',
                'reward_detail' => 'لكل حملة: زيارة فرع واحدة · 2 فيديو ريلز · مجموعتان من الستوري',
                'join_button' => 'انضم إلى مجتمع غالية',
                'explore_button' => 'اكتشف البرنامج',
                'tiers_label' => 'مستويات صناع المحتوى',
                'tiers' => array(
                    array('label' => 'نانو', 'active' => 0), array('label' => 'مايكرو', 'active' => 1),
                    array('label' => 'متوسط', 'active' => 0), array('label' => 'ماكرو', 'active' => 0),
                ),
                'partners_eyebrow' => 'عالم غالية',
                'partners_title' => 'اكسب واستبدل نقاطك مع شركائنا',
                'partners_mobile_prefix' => 'عالم',
                'partners_mobile_suffix' => '',
                'partners_mobile_copy' => 'اكسب واستبدل نقاطك مع شركائنا',
                'partners_label' => 'العلامات التجارية الشريكة لغالية',
                'benefits_eyebrow' => 'صُمم لصنّاع المحتوى',
                'benefits_title' => 'ماذا تستفيد؟',
                'benefits_intro' => '',
                'benefits' => array(
                    array('title' => 'كسب مكافآت مرنة', 'description' => 'أنشئ محتوى عن برنامج ولاء غالية واكسب نقاطًا لإنفاقها بحرية عند العلامات التجارية الشريكة.'),
                    array('title' => 'تنمية جمهورك', 'description' => 'عزّز حضورك واكسب متابعين حقيقيين في المنطقة.'),
                    array('title' => 'شراكات مع علامات رائدة', 'description' => 'احصل على فرص تعاون مدفوعة وهدايا مع ألمع الأسماء.'),
                    array('title' => 'مزايا حصرية للمنتجات', 'description' => 'كن أول من يحصل على هدايا مجانية وإصدارات جديدة ودعوات خاصة.'),
                ),
                'deliver_eyebrow' => 'مهام واضحة',
                'deliver_title' => 'ما ستقدمه لكل حملة',
                'deliverables' => array(
                    array('title' => 'زيارة فرع واحدة', 'description' => 'خض التجربة مع العلامة التجارية بنفسك.'),
                    array('title' => '2 فيديو ريلز / تيك توك', 'description' => 'انشر محتوى فيديو قصير وممتع.'),
                    array('title' => 'مجموعتان من الستوري', 'description' => 'شارك تغطية فورية مع إشارة للروابط المباشرة.'),
                    array('title' => 'دفع سريع', 'description' => 'تُضاف النقاط مباشرة إلى محفظة غالية الخاصة بك.'),
                ),
                'looking_eyebrow' => 'هل أنت مستعد؟',
                'looking_title' => 'من نبحث عنه',
                'requirements' => array(
                    array('text' => 'مقيم في المملكة العربية السعودية'),
                    array('text' => 'أكثر من 1,000 متابع على منصات التواصل'),
                    array('text' => 'صانع محتوى نشط على إنستغرام أو تيك توك'),
                ),
                'categories_title' => 'فئات المحتوى',
                'categories' => array(
                    array('text' => 'طعام'), array('text' => 'سفر'), array('text' => 'طهاة'),
                    array('text' => 'عروض وصفقات'), array('text' => 'جمال'), array('text' => 'لياقة بدنية'),
                    array('text' => 'أسلوب حياة'),
                ),
                'start_button' => 'ابدأ طلبك',
                'faq_eyebrow' => 'الأسئلة الشائعة',
                'faq_title' => 'كل ما تحتاج معرفته',
                'faq_intro' => '',
                'faqs' => array(
                    array('question' => 'هل هناك أي تكلفة للانضمام إلى برنامج غالية لصنّاع المحتوى؟', 'answer' => 'لا، الانضمام إلى غالية كصانع محتوى شريك مجاني 100%. لا توجد رسوم تسجيل أو رسوم منصة أو تكاليف خفية.'),
                    array('question' => 'كيف أستلم أرباحي؟', 'answer' => 'تُضاف المكافآت المعتمدة كنقاط ولاء إلى محفظة غالية المسجلة باسمك.'),
                    array('question' => 'هل أحتاج إلى ترخيص إعلاني سعودي (موثوق)؟', 'answer' => 'يُطلب ترخيص ساري المفعول حيثما تنطبق اللوائح السعودية على المحتوى المدعوم.'),
                    array('question' => 'كم من الوقت يستغرق مراجعة طلبي؟', 'answer' => 'يمكنك توقع الرد خلال 14 يومًا من تقديم الطلب.'),
                    array('question' => 'هل يمكن تحويل نقاط غالية إلى نقد؟', 'answer' => 'لا يمكن تحويل النقاط إلى نقد، ويمكن استبدالها لدى العلامات التجارية الشريكة.'),
                    array('question' => 'ما هي العلامات التجارية المشاركة؟', 'answer' => 'يضم البرنامج أكثر من خمس علامات تجارية رائدة، ويختلف التوفر حسب الحملة.'),
                    array('question' => 'هل يمكنني اختيار المتاجر والعلامات التي أزورها؟', 'answer' => 'يمكنك تحديد العلامات المفضلة وأقرب تاريخ متاح ضمن مقترحك.'),
                    array('question' => 'ما هي حقوق المحتوى التي تحصل عليها العلامات؟', 'answer' => 'يحتفظ صانع المحتوى بالملكية ويمنح حقوق استخدام محدودة وفقًا للشروط.'),
                ),
            ),
            'profile' => array(
                'aside_title' => 'طلب الانضمام إلى غالية',
                'aside_intro' => 'أخبرنا عن جمهورك وأعمالك وتوفرك. لن يستغرق الأمر سوى دقائق.',
                'progress_labels' => ghalya_default_progress_labels('ar'),
                'top_back_label' => 'العودة للرئيسية',
                'step_label' => 'الخطوة 1 من 5',
                'title' => 'ملفك الشخصي',
                'intro' => 'ابدأ بالمعلومات الأساسية لنتمكن من تحديد مستوى الحملة المناسب لك.',
                'full_name_label' => 'الاسم الكامل', 'full_name_placeholder' => 'الاسم الكامل',
                'instagram_label' => 'حساب إنستغرام', 'instagram_placeholder' => '@instagramhandle',
                'followers_label' => 'عدد المتابعين',
                'followers_choices' => ghalya_default_choice_rows(array('1-10K' => '1–10 آلاف', '10K-50K' => '10–50 ألف', '50K-500K' => '50–500 ألف', '500K+' => '500 ألف+')),
                'city_label' => 'المدينة', 'city_placeholder' => 'اختر المدينة',
                'city_choices' => ghalya_default_choice_rows(array('Riyadh' => 'الرياض', 'Jeddah' => 'جدة', 'Dammam' => 'الدمام', 'Other' => 'أخرى')),
                'category_label' => 'فئة المحتوى',
                'category_choices' => ghalya_default_choice_rows(array('Food' => 'طعام', 'Cooking' => 'طهي', 'Lifestyle' => 'أسلوب حياة', 'Beauty' => 'جمال', 'Fitness' => 'لياقة بدنية', 'Travel' => 'سفر', 'Offers' => 'عروض')),
                'back_button' => 'إلغاء', 'next_button' => 'متابعة',
            ),
            'tier' => array(
                'aside_title' => 'طلب الانضمام إلى غالية',
                'aside_intro' => 'يعكس مستوى البداية نطاق جمهورك وفئة المحتوى المختارة.',
                'progress_labels' => ghalya_default_progress_labels('ar'),
                'top_back_label' => 'السابق', 'step_label' => 'الخطوة 2 من 5',
                'title' => 'مستواك', 'intro' => 'هذا هو مستوى البداية المخصص لك للحملة.',
                'tier_name' => 'صانع محتوى مايكرو', 'tier_amount' => '2,000 ريال', 'tier_suffix' => 'كنقاط ولاء في غالية',
                'deliverables_label' => 'المهام المتوقعة',
                'deliverables' => array(array('text' => 'زيارة فرع واحدة'), array('text' => '2 فيديو ريلز'), array('text' => 'مجموعتان من الستوري')),
                'note' => 'بناءً على عدد متابعيك وفئة ملفك الشخصي، هذا هو مستوى البداية المخصص لك. يمكن استبدال نقاط غالية لدى أكثر من 5 علامات تجارية شريكة في المملكة.',
                'back_button' => 'رجوع', 'next_button' => 'متابعة',
            ),
            'work' => array(
                'aside_title' => 'طلب الانضمام إلى غالية',
                'aside_intro' => 'شارك القنوات والمحتوى الذي يمثل أسلوبك الإبداعي.',
                'progress_labels' => ghalya_default_progress_labels('ar'),
                'top_back_label' => 'السابق', 'step_label' => 'الخطوة 3 من 5',
                'title' => 'أعمالك', 'intro' => 'أضف حساباتك العامة ومثالًا لمحتوى سابق للعلامات التجارية إن توفر.',
                'instagram_label' => 'رابط حساب إنستغرام', 'instagram_placeholder' => 'رابط حساب إنستغرام',
                'tiktok_label' => 'رابط حساب تيك توك', 'tiktok_placeholder' => 'رابط حساب تيك توك',
                'snapchat_label' => 'اسم مستخدم سناب شات', 'snapchat_placeholder' => 'اسم مستخدم سناب شات',
                'brand_content_label' => 'محتوى سابق للعلامات', 'brand_content_placeholder' => 'رابط المحتوى',
                'add_link_button' => '+ إضافة رابط آخر', 'back_button' => 'رجوع', 'next_button' => 'متابعة',
            ),
            'proposal' => array(
                'aside_title' => 'طلب الانضمام إلى غالية',
                'aside_intro' => 'اختر العلامات التي ترغب في العمل معها وحدد وقت توفرك.',
                'progress_labels' => ghalya_default_progress_labels('ar'),
                'top_back_label' => 'السابق', 'step_label' => 'الخطوة 4 من 5',
                'title' => 'مقترحك', 'intro' => 'حدد علامة واحدة أو أكثر ترغب في صناعة المحتوى لها.',
                'brands_label' => 'حدد العلامات التجارية',
                'brand_choices' => ghalya_default_choice_rows(array('Danube' => 'Danube', 'BinDawood' => 'BinDawood', 'Delsey' => 'Delsey', 'Kipling' => 'Kipling', 'Zahrat Al Rawdah' => 'Zahrat Al Rawdah')),
                'availability_label' => 'أقرب تاريخ متاح', 'back_button' => 'رجوع', 'next_button' => 'متابعة',
            ),
            'contact' => array(
                'aside_title' => 'خطوة أخيرة',
                'aside_intro' => 'أضف تفاصيل التواصل وراجع شروط البرنامج قبل تقديم الطلب.',
                'progress_labels' => ghalya_default_progress_labels('ar'),
                'top_back_label' => 'السابق', 'step_label' => 'الخطوة 5 من 5',
                'title' => 'تفاصيل التواصل', 'intro' => 'كيف يمكن لفريق غالية التواصل معك بشأن هذه الحملة؟',
                'email_label' => 'البريد الإلكتروني', 'email_placeholder' => 'email@email.com',
                'phone_label' => 'رقم الجوال', 'phone_placeholder' => '+966 0000 0000',
                'consent_before' => 'أوافق على', 'consent_link' => 'شروط وأحكام غالية',
                'consent_after' => 'وأسمح لغالية بالتواصل معي بشأن هذه الحملة.',
                'back_button' => 'رجوع', 'submit_button' => 'تقديم الطلب',
            ),
            'success' => array(
                'eyebrow' => 'اكتمل الطلب', 'title' => 'تم تقديم الطلب!',
                'message' => 'شكرًا لاهتمامك بالانضمام إلى مجتمع غالية. يتوقع الرد خلال 14 يومًا.',
                'social_handle' => '@ghalyaloyalty', 'back_button' => 'العودة إلى غالية',
            ),
            'terms' => array(
                'eyebrow' => 'برنامج غالية لصنّاع المحتوى', 'title' => 'الشروط والأحكام',
                'intro' => 'تنظم هذه الشروط والأحكام مشاركة صنّاع المحتوى في برنامج غالية لصنّاع المحتوى الذي تديره غالية.',
                'sections' => array(
                    array('title' => '1. القبول بالشروط والأهلية', 'body' => 'بتقديم طلبك، فإنك تقر بأن عمرك لا يقل عن 18 عامًا وأنك تقيم في المملكة العربية السعودية، وأن جميع المعلومات المقدمة دقيقة وصحيحة، وأنك حاصل على ترخيص إعلاني سعودي ساري المفعول (موثوق) حيثما يُشترط ذلك قانونًا للمحتوى الرقمي المدعوم أو الترويجي.'),
                    array('title' => '2. الاختيار وتحديد المستوى', 'body' => 'تقديم الطلب لا يضمن القبول. تحتفظ غالية بالحق في اختيار صنّاع المحتوى بناءً على احتياجات الحملة وجودة المحتوى والحصص الشهرية. يتم حساب المستويات بناءً على عدد المتابعين ومعدلات التفاعل وفئة المحتوى، ويحق لغالية تعديل التصنيفات أو المكافآت للحملات المستقبلية.'),
                    array('title' => '3. تسليمات الحملة والموافقات', 'body' => 'عند القبول في حملة معينة، يوافق صانع المحتوى على إكمال جميع التسليمات وفقًا لملخص الحملة وإرشاداتها. يجب تقديم المحتوى إلى غالية للحصول على موافقة مسبقة قبل النشر، وأن يظل محترمًا وأصيلًا ومتوافقًا مع الأنظمة السعودية والأعراف الثقافية وخاليًا من انتهاكات حقوق الغير.'),
                    array('title' => '4. المكافآت والدفع', 'body' => 'تُصدر المكافآت حصرًا على شكل نقاط ولاء في غالية وتُضاف إلى المحفظة الرقمية المسجلة بعد التحقق من التسليمات واعتمادها. النقاط غير قابلة للنقل أو التحويل إلى مبالغ نقدية، ويمكن استبدالها بمنتجات أو قسائم أو خدمات لدى الشركاء وفقًا للتوفر وسياسات انتهاء الصلاحية.'),
                    array('title' => '5. حقوق المحتوى وترخيص الاستخدام', 'body' => 'يحتفظ صانع المحتوى بملكية المحتوى الأصلي. وبنشر محتوى الحملة يمنح غالية والعلامات المشاركة ترخيصًا غير حصري وعالمي ومعفيًا من الإتاوات لإعادة مشاركة وتضمين ونشر المحتوى عبر قنواتهم الرقمية لمدة قياسية تبلغ 90 يومًا عقب انتهاء الحملة.'),
                    array('title' => '6. خصوصية البيانات والموافقة على التواصل', 'body' => 'بالموافقة في نموذج الطلب، تمنح غالية الإذن بجمع بياناتك الشخصية وتخزينها ومعالجتها لتقييم طلبك والتواصل معك عبر واتساب أو الرسائل النصية أو البريد الإلكتروني بشأن فرص الحملات النشطة والمستقبلية.'),
                ),
                'start_button' => 'ابدأ الطلب', 'back_button' => 'العودة للرئيسية',
            ),
        ),
    );

    return isset($defaults[$language][$screen]) ? $defaults[$language][$screen] : array();
}

function ghalya_default_progress_labels($language)
{
    $labels = $language === 'ar'
        ? array('الملف الشخصي', 'المستوى', 'أعمالك', 'المقترح', 'التواصل')
        : array('Profile', 'Tier', 'Work', 'Proposal', 'Contact');

    return array_map(function ($label) {
        return array('label' => $label);
    }, $labels);
}

function ghalya_default_choice_rows($choices)
{
    $rows = array();

    foreach ($choices as $value => $label) {
        $rows[] = array('value' => $value, 'label' => $label);
    }

    return $rows;
}
